# Generated by Django 4.0.2 on 2022-03-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Organizacao',
            new_name='organizacao',
        ),
    ]
