# Generated by Django 4.0.2 on 2022-02-21 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=3, unique=True)),
                ('regional', models.CharField(choices=[('BGI', 'Recife'), ('NTD', 'Natal'), ('PTU', 'Salvador'), ('FTZ', 'Fortaleza'), ('SBD', 'Sobradinho'), ('PAF', 'Paulo Afonso')], default='BGI', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('RG', 'Órgão regulador'), ('GV', 'Órgão governamental'), ('CH', 'Órgão interno Chesf'), ('FN', 'Fornecedor'), ('OU', 'Outro')], default='CH', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RA', 'Resolução Autorizativa'), ('R4', 'Relatório R4'), ('OF', 'Ofício'), ('NT', 'Nota Técnica'), ('PR', 'Relatório PRORET'), ('DP', 'Despacho'), ('ET', 'Especificação Técnica'), ('OU', 'Outro')], max_length=2)),
                ('codigo', models.CharField(max_length=50, verbose_name='código')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('data_doc', models.DateField(blank=True, null=True, verbose_name='data do documento')),
                ('instalacoes', models.ManyToManyField(blank=True, null=True, to='gpt.Instalacoes')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gpt.origem')),
            ],
        ),
    ]
