# Generated by Django 4.0.2 on 2022-02-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentos',
            new_name='Documento',
        ),
        migrations.RenameModel(
            old_name='Instalacoes',
            new_name='Instalacao',
        ),
    ]
