# Generated by Django 4.0.2 on 2022-02-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0002_rename_documentos_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='tipo',
            field=models.CharField(choices=[('US', 'Usina'), ('SE', 'Subestação')], default='SE', max_length=2),
        ),
    ]
