# Generated by Django 4.0.2 on 2022-02-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0004_documento_criado_em_instalacao_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='origem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
