# Generated by Django 4.0.2 on 2022-02-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0006_documento_referencias_alter_documento_instalacoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ('-criado_em',)},
        ),
        migrations.AlterModelOptions(
            name='instalacao',
            options={'ordering': ('-criado_em',)},
        ),
        migrations.AlterModelOptions(
            name='origem',
            options={'ordering': ('-criado_em',)},
        ),
        migrations.AddField(
            model_name='documento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instalacao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='origem',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
