# Generated by Django 4.0.2 on 2022-02-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0010_alter_documento_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arq'),
        ),
    ]
