# Generated by Django 4.0.2 on 2022-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0016_organizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
