# Generated by Django 4.0.2 on 2022-03-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0019_alter_documento_origem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacao',
            options={'ordering': ('nome',)},
        ),
    ]
